### ISSUE TITLE
Segmentation fault when attempting to make (Mac M1) 

### ISSUE THREAD

**Issue by aj-page** [njoy/NJOY21#163] opened 2022-04-18 02:06 UTC
Warning: Array reference at (1) out of bounds (-2 < 1) in loop beginning at (2) [-Wdo-subscript]
[ 28%] Building Fortran object _deps/njoy-build/CMakeFiles/njoy.dir/src/errorr.f90.o
f951: internal compiler error: Segmentation fault: 11
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://github.com/Homebrew/homebrew-core/issues> for instructions.
make[2]: *** [_deps/njoy-build/CMakeFiles/njoy.dir/src/errorr.f90.o] Error 1
make[1]: *** [_deps/njoy-build/CMakeFiles/njoy.dir/all] Error 2
make: *** [all] Error 2

**Comment by whaeck** [comment] 2022-04-18 02:44
There is a known issue within the gcc-11 compiler that causes an internal compiler error when compiling NJOY's ERRORR module. For more details on this, see issue #162 and NJOY2016 issue [211](https://github.com/njoy/NJOY2016/issues/211).

There is nothing that can be done to fix this other than switching to either gcc-7 up to and including gcc-10 or gcc-12. Since this issue has been reported on before, I'll be closing this particular issue as it is a duplicate of issue #163.

We will be updating the NJOY release note to exclude support for gcc-11.

**Closed by whaeck** 2022-04-18 02:44 UTC
